version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - .db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=performer
      - MYSQL_DATABASE=ctfmanagerDb
    ports:
      - "3306:3306"
    networks:
        webpage:
            ipv4_address: 172.25.0.5

networks:
  webpage:
      ipam:
        config:
          - subnet: 172.25.0.0/16
