version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - .db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=performer
      - MYSQL_DATABASE=ctfmanagerDb
    ports:
      - "3306:3306"
    networks:
      - webpage
    

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stefvanremoortele/ctfmanager
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - webpage

networks:
  webpage:
