# Generated by Django 2.1.1 on 2018-10-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='owner',
        ),
    ]
