# Generated by Django 2.1.2 on 2018-10-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0002_auto_20181007_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=models.CharField(blank=True, choices=[('REV', 'Reverse Engineering'), ('MISC', 'Miscellaneous'), ('CRYPTO', 'Cryptography'), ('WEB', 'Web Applications'), ('PUZZLE', 'Puzzles')], default=('MISC', 'Miscellaneous'), max_length=6),
        ),
    ]
