# Generated by Django 2.1.1 on 2018-10-05 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0002_remove_hackathon_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='solvers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
