# Generated by Django 2.1.1 on 2018-10-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0004_auto_20181005_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='hackathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ctfman.Hackathon'),
            preserve_default=False,
        ),
    ]
