# Generated by Django 2.1.2 on 2018-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0006_auto_20181006_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
