# Generated by Django 2.1.2 on 2018-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0007_hackathon_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='rating',
            field=models.IntegerField(default='1'),
        ),
    ]
