# Generated by Django 2.1.2 on 2018-10-14 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0010_logevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logevent',
            old_name='logMessage',
            new_name='message',
        ),
        migrations.AddField(
            model_name='logevent',
            name='fileName',
            field=models.CharField(default='main.js', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logevent',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logevent',
            name='lineNumber',
            field=models.CharField(default='3', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
