# Generated by Django 2.1.2 on 2018-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0011_auto_20181014_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='rating',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
