# Generated by Django 2.1.2 on 2018-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0012_auto_20181026_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
