# Generated by Django 2.1.2 on 2018-10-26 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctfman', '0013_auto_20181026_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
